'''
Created on Nov 20, 2017

@author: Edward C. (MorningOwl)
'''
from random import randint

def main():   
    
    print("Welcome to a game of Hack-the-Code. The game is simple: a 4-digit code is generated by system") 
    print("and you must guess it before the security shuts you down! For every guess, the system will")
    print("respond with 3 signals and each signal will contain an x counter:\n")
    print("Green signifies that an x number of positions were correct. ")
    print("Yellow signifies that an x number of digits were correct, but the positions were wrong. ")
    print("Red signifies that an x number of digits guessed are not in the secret code.\n")
    print("The game ends when you have attempted 10 tries or when you have guessed the code!\n")
    while True:
        print("A new code has been generated. Start the guessing!")
        code = create_new_code()
        guesses_left = 10
        #round while loop
        while True:
            #guess while loop       
            while True:
                guess_all_digits = True 
                guess = input("Guess 4-digit code: ")            
                try:
                    int(guess)
                except (TypeError, ValueError):
                    guess_all_digits = False
                if(len(guess) == 4 and guess_all_digits):
                    break
            answer = [int(guess[0]),int(guess[1]),int(guess[2]),int(guess[3])]   
            result = check_answer(code, answer)
            print("Green light: " + str(result[0]) + "|| Yellow light: " + str(result[1]) + "|| Red light: " + str(result[2]))
            guesses_left -= 1
            if(result[0] == 4):
                print("Code hacked! The code was: " + str(code));
                break
            elif(guesses_left <= 0):
                print("Security caught you, game over! The code was: " + str(code))
                break
        #round finished
        #ask for new game
        play_again = input("Would you like to play again? (y/n): ")
        while (play_again != "y" and play_again != "n"):
            play_again = input("Would you like to play again? (y/n): ")
            play_again = play_again.lstrip()
            play_again = play_again.rstrip()
        if(play_again == "y"):
            pass
        else:
            print("Thanks for playing!")
            break
        
""""
Create a new code
"""
def create_new_code():
    code = [0] * 4
    code[0] = randint(0,9)
    code[1] = randint(0,9)
    code[2] = randint(0,9)
    code[3] = randint(0,9)
    return code

""""
Check the answer with the guess and return result
"""
def check_answer(guess, answer):
    green_light = 0
    yellow_light = 0
    red_light = 0
    guesses_left = []
    answers_left = []
    for i in range(0, len(answer)):
        if(guess[i] == answer[i]):
            green_light += 1
        else:
            guesses_left.append(guess[i])
            answers_left.append(answer[i])
    for j in range(0, len(answers_left)):
        if answers_left[j] in guesses_left:
            yellow_light += 1
            guesses_left.remove(answers_left[j])
    red_light += len(guess) - green_light - yellow_light    
    return [green_light, yellow_light, red_light]  

if __name__ == '__main__':
    main()
    
    
